import { useState, useEffect } from 'react';
import { Activity, ShieldCheck, HeartPulse } from 'lucide-react';
import { callClaude } from '../api';

const Skeleton = () => (
  <div className="space-y-6 animate-pulse">
    {[1, 2, 3].map((i) => (
      <div key={i} className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex gap-4">
        <div className="w-12 h-12 bg-gray-200 rounded-xl shrink-0"></div>
        <div className="flex-1 space-y-3 py-1">
          <div className="h-4 bg-gray-200 rounded w-1/4"></div>
          <div className="h-3 bg-gray-200 rounded w-full"></div>
          <div className="h-3 bg-gray-200 rounded w-5/6"></div>
        </div>
      </div>
    ))}
  </div>
);

export default function HealthSummary() {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const prompt = "Please provide a friendly, plain-English daily health summary based on my metrics. Structure it into exactly 3 short paragraphs: 1. What's good (praise positive metrics), 2. What's concerning (gentle flag on BP/sleep/stress), 3. What to do today (actionable but simple steps). Do not use markdown headers, just return the paragraphs separated by newlines.";
        
        const response = await callClaude(prompt);
        // Split by double newlines or single newlines
        const paragraphs = response.split(/\n+/).filter(p => p.trim().length > 0).slice(0, 3);
        setSummary(paragraphs);
      } catch (err) {
        setError(err.message || "Failed to load summary.");
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, []);

  const icons = [
    { icon: ShieldCheck, color: 'text-brand-green', bg: 'bg-green-50', title: "What's Good" },
    { icon: Activity, color: 'text-amber-500', bg: 'bg-amber-50', title: "What Needs Attention" },
    { icon: HeartPulse, color: 'text-brand-blue', bg: 'bg-blue-50', title: "Action Plan for Today" },
  ];

  return (
    <div className="max-w-3xl mx-auto pb-24 md:pb-8">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 tracking-tight">AI Health Summary</h2>
        <p className="text-gray-500 mt-1">Your daily personalized insights generated by HealthBuddy.</p>
      </div>

      {loading ? (
        <Skeleton />
      ) : error ? (
        <div className="bg-red-50 p-6 rounded-2xl text-red-700 border border-red-100">
          <p className="font-semibold mb-2">Oops, something went wrong.</p>
          <p className="text-sm">{error}</p>
        </div>
      ) : (
        <div className="space-y-6">
          {summary.map((para, index) => {
            const IconGroup = icons[Math.min(index, icons.length - 1)];
            const Icon = IconGroup.icon;
            
            return (
              <div key={index} className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow flex gap-5">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${IconGroup.bg}`}>
                  <Icon className={`w-6 h-6 ${IconGroup.color}`} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-gray-900 mb-2">{IconGroup.title}</h3>
                  <p className="text-gray-600 leading-relaxed">{para}</p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
