import { useState, useEffect } from 'react';
import { ShieldCheck, Activity, Lightbulb, RefreshCw } from 'lucide-react';
import { useAppContext } from '../AppContext';

const Skeleton = () => (
  <div className="space-y-4 animate-pulse">
    {[1, 2, 3].map((i) => (
      <div key={i} className="bg-white p-5 rounded-2xl border border-gray-100 flex gap-4">
        <div className="w-10 h-10 bg-gray-200 rounded-lg shrink-0"></div>
        <div className="flex-1 space-y-2 py-1">
          <div className="h-4 bg-gray-200 rounded w-1/3"></div>
          <div className="h-3 bg-gray-200 rounded w-full"></div>
          <div className="h-3 bg-gray-200 rounded w-5/6"></div>
        </div>
      </div>
    ))}
  </div>
);

export default function HealthSummary() {
  const { callOpenAI } = useAppContext();
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchSummary = async () => {
    setLoading(true);
    setError(null);
    try {
      const prompt = "Give Raj a daily health summary with exactly 3 sections: 'What looks good', 'What needs attention', 'Top 2 tips for today'. Provide 2-3 sentences each. Do not use markdown headers, just return the paragraphs separated by double newlines.";
      const response = await callOpenAI(prompt);
      const paragraphs = response.split(/\n+/).filter(p => p.trim().length > 0).slice(0, 3);
      setSummary(paragraphs);
    } catch (err) {
      setError(err.message || "Failed to load summary.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const sections = [
    { icon: ShieldCheck, color: 'text-brand-green', bg: 'bg-green-50', title: "What looks good" },
    { icon: Activity, color: 'text-brand-red', bg: 'bg-red-50', title: "What needs attention" },
    { icon: Lightbulb, color: 'text-brand-blue', bg: 'bg-blue-50', title: "Top 2 tips for today" },
  ];

  return (
    <div className="p-4">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-xl font-bold text-gray-900 tracking-tight">AI Health Summary</h2>
          <p className="text-gray-500 text-xs mt-1">Generated by GPT-4o</p>
        </div>
        <button 
          onClick={fetchSummary}
          disabled={loading}
          className="p-2 bg-white rounded-lg shadow-sm border border-gray-200 text-gray-600 hover:text-brand-blue transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {loading ? (
        <Skeleton />
      ) : error ? (
        <div className="bg-red-50 p-4 rounded-xl text-brand-red border border-red-100 text-sm">
          <p className="font-bold mb-1">Failed to generate summary</p>
          <p>{error}</p>
        </div>
      ) : (
        <div className="space-y-4">
          {summary && summary.map((para, index) => {
            const Section = sections[Math.min(index, sections.length - 1)];
            const Icon = Section.icon;
            
            return (
              <div key={index} className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
                <div className="flex items-center gap-3 mb-2">
                  <div className={`p-2 rounded-lg ${Section.bg}`}>
                    <Icon className={`w-5 h-5 ${Section.color}`} />
                  </div>
                  <h3 className="font-bold text-gray-900 text-sm">{Section.title}</h3>
                </div>
                <p className="text-gray-600 text-sm leading-relaxed">
                  {para.replace(/^(what looks good|what needs attention|top 2 tips for today):/i, '').trim()}
                </p>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
