import { useState } from 'react';
import { ShieldCheck, Activity, Lightbulb, RefreshCw } from 'lucide-react';
import Typewriter from '../components/Typewriter';
import { HARDCODED_RESPONSES } from '../data';

export default function HealthSummary() {
  const [triggerKey, setTriggerKey] = useState(0);

  const sections = [
    { icon: ShieldCheck, color: 'text-brand-green', bg: 'bg-green-50' },
    { icon: Activity, color: 'text-brand-red', bg: 'bg-red-50' },
    { icon: Lightbulb, color: 'text-brand-blue', bg: 'bg-blue-50' },
  ];

  const handleRefresh = () => {
    setTriggerKey(k => k + 1);
  };

  return (
    <div className="p-4">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-xl font-bold text-gray-900 tracking-tight">AI Health Summary</h2>
          <p className="text-gray-500 text-xs mt-1">Generated by HealthBuddy AI</p>
        </div>
        <button 
          onClick={handleRefresh}
          className="p-2 bg-white rounded-lg shadow-sm border border-gray-200 text-gray-600 hover:text-brand-blue transition-colors"
        >
          <RefreshCw className="w-5 h-5" />
        </button>
      </div>

      <div className="space-y-4">
        {HARDCODED_RESPONSES.summary.map((section, index) => {
          const UISection = sections[index % sections.length];
          const Icon = UISection.icon;
          
          return (
            <div key={`${index}-${triggerKey}`} className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
              <div className="flex items-center gap-3 mb-3">
                <div className={`p-2 rounded-lg ${UISection.bg}`}>
                  <Icon className={`w-5 h-5 ${UISection.color}`} />
                </div>
                <h3 className="font-bold text-gray-900 text-sm">{section.title}</h3>
              </div>
              <div className="text-gray-600">
                <Typewriter text={section.text} delay={1200 + (index * 200)} />
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
